apiVersion: v1
kind: Service
metadata:
    name: api-http
    namespace: default
spec:
    type: NodePort
    selector:
        name: api-app
    ports:
        - port: 8000
          targetPort: 80
          nodePort: 32222